# Generated by Django 3.2.11 on 2022-04-30 01:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220427_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment_report',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment_report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='Donation',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project_report',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project_report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='projcet_id',
            new_name='projcet',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='project_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
