# Generated by Django 3.2.11 on 2022-04-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220430_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
