# Generated by Django 3.2.11 on 2022-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
