# Generated by Django 3.2.11 on 2022-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_report',
            name='report',
            field=models.CharField(choices=[('ip', 'inappropriate'), ('ags', 'aggressive')], default='ip', max_length=200),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=30),
        ),
    ]
