# Generated by Django 3.2.11 on 2022-05-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220430_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_report',
            name='report',
            field=models.CharField(choices=[('ip', 'inappropriate'), ('ags', 'aggressive')], default='ip', max_length=200),
        ),
    ]
