# Generated by Django 3.2.11 on 2022-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='photo'),
        ),
    ]
