# Generated by Django 3.2.11 on 2022-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_register_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='user/images/', verbose_name='photo'),
        ),
    ]
